[package]
name = "imgui-boirplate"
version = "0.1.0"
authors = ["metalneox <codematrix@altervista.org>"]
edition = "2018"


[dependencies]
glium = "0.26.0"
clipboard = "0.5.0"
imgui = "0.3.0"
imgui-glium-renderer = "0.3.0"
imgui-winit-support = "0.3.1"
